apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: colisnc-api
spec:
  template:
    metadata:
      # This is the name of our new "Revision," it must follow the convention {service-name}-{revision-name}
      name: colisnc-api-stable
    spec:
      containers:
        - image: optnc/colisnc-api:stable
          ports:
            - containerPort: 8080