name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Prepare tags
        id: image_tags
        run: |
          VERSION=$(git describe --tags --exact-match 2>/dev/null || true)
          if [[ $VERSION ]]; then
          echo ::set-output name=tags::"latest,stable,${VERSION##v}"
          else
          echo ::set-output name=tags::"latest"
          fi

      - name: Publish on Docker Hub with
        run: mvn -B -Djib.to.auth.username=${{secrets.OPT_DOCKERHUB_LOGIN}} -Djib.to.auth.password=${{secrets.OPT_DOCKERHUB_PASSWORD}} -Djib.to.tags=${{steps.image_tags.outputs.tags}} compile jib:build
